"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import "./accept.css";
type Invitation={email:string;name:string;role:string;channel:string;expiresAt:string};
export default function AcceptPage(){
 const[token,setToken]=useState(""),[invitation,setInvitation]=useState<Invitation|null>(null),[firstName,setFirstName]=useState(""),[lastName,setLastName]=useState(""),[email,setEmail]=useState(""),[company,setCompany]=useState(""),[state,setState]=useState<"loading"|"ready"|"working"|"done"|"error">("loading"),[message,setMessage]=useState("");
 useEffect(()=>{void(async()=>{const value=new URLSearchParams(location.search).get("token")||"";const response=await fetch(`/api/invitations/accept?token=${encodeURIComponent(value)}`),data=await response.json();setToken(value);if(response.ok){setInvitation(data.invitation);setEmail(data.invitation.email);setState("ready")}else{setMessage(data.error);setState("error")}})()},[]);
 const accept=async()=>{setState("working");const response=await fetch("/api/invitations/accept",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,firstName,lastName,email,company})}),data=await response.json();if(response.ok){setState("done");setMessage(`Welcome, ${data.user.name} from ${data.user.companyName}. Your account is ready.`)}else{setState("error");setMessage(data.error)}};
 return <main className="onboard"><section className="onboard-card"><div className="onboard-logo">Task <b>AI</b></div>{state==="loading"?<p>Checking invitation…</p>:state==="done"?<><span className="success-mark">✓</span><h1>Account verified</h1><p>{message}</p><Link className="onboard-primary" href="/">Check my tasks →</Link></>:state==="error"&&!invitation?<><h1>Invitation unavailable</h1><p className="onboard-error">{message}</p></>:<><p>VERIFY YOUR ACCOUNT</p><h1>Finish your profile</h1><p>Confirm who you are to access the tasks and work areas shared with you.</p>{invitation&&<div className="invite-context"><b>{invitation.role.replace("_"," ")}</b><span>Invitation sent by {invitation.channel} · expires {new Date(invitation.expiresAt).toLocaleDateString("en-GB")}</span></div>}<div className="onboard-form"><div className="onboard-two"><Field title="First name"><input autoComplete="given-name" value={firstName} onChange={e=>setFirstName(e.target.value)}/></Field><Field title="Last name"><input autoComplete="family-name" value={lastName} onChange={e=>setLastName(e.target.value)}/></Field></div><Field title="Company name"><input autoComplete="organization" value={company} onChange={e=>setCompany(e.target.value)} placeholder="Your company or organization"/></Field><Field title="Verified email address"><input className="verified-email" type="email" value={email} readOnly/><small>✓ Verified by your secure invitation link</small></Field>{state==="error"&&<p className="onboard-error">{message}</p>}<button className="onboard-primary" disabled={state==="working"||!firstName.trim()||!lastName.trim()||!company.trim()} onClick={accept}>{state==="working"?"Verifying account…":"Verify profile & check my tasks"}</button></div></>}</section></main>;
}
function Field({title,children}:{title:string;children:React.ReactNode}){return <label className="onboard-field"><span>{title}</span>{children}</label>}
