// @ts-nocheck -- preserved prototype UI; production boundaries are typed and tested.
"use client";
import { useEffect, useMemo, useState } from "react";
import ContactPicklist from "../components/ContactPicklist";
import "./users.css";
type Role="site_admin"|"area_admin"|"collaborator"|"readonly";
type ActivityCounts={active:number;passive:number;score:number};
type Activity={last30Days:ActivityCounts;allTime:ActivityCounts};
type User={id:number;email:string;name:string;company_name?:string;email_verified_at?:string;phone?:string;invite_channel?:"email"|"whatsapp";invite_expires_at?:string;role:Role;status:"pending"|"active"|"revoked";canInvite:boolean;projects:string[];meetings:string[];topics:string[];last_active_at?:string|null;email_status?:string|null;email_status_detail?:string|null;email_status_at?:string|null;activity?:Activity};
// Active work (editing, status updates, creating a task) outweighs just
// viewing one 3:1 server-side (see app/lib/activity-meter.ts) — this only
// turns that score into a bar width, relative to whoever's busiest right
// now rather than a fixed scale, so the meter stays meaningful whether
// there are 5 tasks in the company or 5,000.
const activityPct=(user:User,maxScore:number)=>maxScore?Math.round(((user.activity?.last30Days.score||0)/maxScore)*100):0;
const activityTitle=(user:User)=>{const a=user.activity;if(!a)return"No activity tracked yet";return`Last 30 days: ${a.last30Days.active} active action${a.last30Days.active===1?"":"s"}, ${a.last30Days.passive} view${a.last30Days.passive===1?"":"s"} · All-time: ${a.allTime.active} active action${a.allTime.active===1?"":"s"}, ${a.allTime.passive} view${a.allTime.passive===1?"":"s"}`};
const deliveryBadge=(user:User)=>{if(user.invite_channel!=="email"||!user.email_status)return null;const copy:Record<string,{label:string;title:string}>={delivered:{label:"✓ Delivered",title:"Resend confirmed this invitation reached the recipient's mail server."},bounced:{label:"⚠ Bounced",title:user.email_status_detail||"Resend reported this invitation could not be delivered — check the email address."},complained:{label:"⚠ Marked as spam",title:user.email_status_detail||"The recipient's provider reported this as spam."},delayed:{label:"⏳ Delivery delayed",title:user.email_status_detail||"Resend is retrying delivery."}};const info=copy[user.email_status];return info?<small className={`delivery-badge ${user.email_status}`} title={info.title}>{info.label}</small>:null};
const lastActive=(iso?:string|null)=>{if(!iso)return"Never signed in";const then=new Date(iso).getTime(),minutes=Math.round((Date.now()-then)/60000);if(minutes<1)return"Active just now";if(minutes<60)return`Active ${minutes}m ago`;if(minutes<1440)return`Active ${Math.round(minutes/60)}h ago`;return`Last active ${new Date(iso).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}`};
type Dimension={id:number;type:"project"|"meeting"|"topic"|"person";value:string};
const roleNames:Record<Role,string>={site_admin:"Site Admin",area_admin:"Project / Meeting Admin",collaborator:"Collaborator",readonly:"Read-only recipient"};
export default function UsersPage(){
 const[users,setUsers]=useState<User[]>([]),[dimensions,setDimensions]=useState<Dimension[]>([]),[editing,setEditing]=useState<User|null>(null),[inviteOpen,setInviteOpen]=useState(false),[link,setLink]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{const response=await fetch("/api/users");const data=await response.json();if(response.ok){setUsers(data.users);setDimensions(data.dimensions)}else setNotice(data.error)};
 useEffect(()=>{void load()},[]);
 // Deep link from a task's "Invite {name}" action (TaskApp.js) — opens
 // straight to a pre-filled invitation instead of a blank form.
 const[inviteName,setInviteName]=useState("");
 useEffect(()=>{const name=new URLSearchParams(location.search).get("invite");if(name){setInviteName(name);setInviteOpen(true);setLink("")}},[]);
 const pending=users.filter(user=>user.status==="pending"),active=users.filter(user=>user.status!=="pending");
 const maxActivityScore=Math.max(1,...users.map(user=>user.activity?.last30Days.score||0));
 const save=async(user:User)=>{const response=await fetch("/api/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(user)});const data=await response.json();if(response.ok){setUsers(items=>items.map(item=>item.id===data.user.id?data.user:item));setEditing(null);setNotice("Access rights saved") }else setNotice(data.error)};
 const notify=async(user:User)=>{const response=await fetch("/api/users/notify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId:user.id})});const data=await response.json();setNotice(response.ok?(data.sent?`Sent ${user.name} their pending tasks (${data.count})`:`Not sent — ${data.reason||"Resend isn't configured yet"}`):data.error)};
 const resend=async(user:User)=>{const response=await fetch("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:user.email,name:user.name,phone:user.phone,inviteChannel:user.invite_channel,role:user.role,canInvite:user.canInvite,projects:user.projects,meetings:user.meetings,topics:user.topics})});const data=await response.json();if(!response.ok){setNotice(data.error);return}setUsers(items=>items.map(item=>item.id===data.user.id?data.user:item));if(data.channel==="whatsapp"){await navigator.clipboard.writeText(`${location.origin}${data.inviteLink}`);setNotice("New invitation link copied — paste it into WhatsApp")}else setNotice(data.delivery?.sent?`Invitation resent to ${user.email}`:`Invitation refreshed, but the email didn't send — ${data.delivery?.reason||"unknown reason"}`)};
 // Workaround for Resend not reliably reaching some inboxes — regenerates
 // a fresh invite token/link the same way resend() does, then hands off
 // to the admin's own email client via mailto: instead of going through
 // Resend at all, so delivery rides on whatever mail setup already works
 // for them (their own domain reputation, their own inbox relationship
 // with the recipient). A new link every click, same as resend() — the
 // old one this replaces stops working, so this can't leave two valid
 // links floating around.
 const emailMyself=async(user:User)=>{const response=await fetch("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:user.email,name:user.name,phone:user.phone,inviteChannel:user.invite_channel,role:user.role,canInvite:user.canInvite,projects:user.projects,meetings:user.meetings,topics:user.topics})});const data=await response.json();if(!response.ok){setNotice(data.error);return}setUsers(items=>items.map(item=>item.id===data.user.id?data.user:item));const link=`${location.origin}${data.inviteLink}`,subject=encodeURIComponent(`You're invited to Task AI`),body=encodeURIComponent(`Hi ${user.name},\n\nYou've been invited to Task AI. Click the link below to set up your account and sign in for the first time:\n\n${link}\n\nThis link is single-use and expires in seven days.\n`);window.location.href=`mailto:${user.email}?subject=${subject}&body=${body}`;setNotice(`Opened your email client with a fresh invite link for ${user.email}`)};
 return <main className="users-shell"><aside className="users-side"><a className="users-logo" href="/">Task <b>AI</b></a><nav><a href="/">← Action items</a><a className="active" href="/users">Users & access</a><a href="/data-hygiene">Data Hygiene</a><a href="/integrations">Integrations</a><a href="/email-preview">Email notifications</a></nav><div className="signed"><span>RF</span><div><b>Rizan Flenner</b><small>Site Admin</small></div></div></aside><section className="users-work"><header><div><label>ADMINISTRATION</label><h1>Users & access</h1><p>Invite people and control exactly which work areas they can access.</p></div><button className="invite" onClick={()=>{setInviteOpen(true);setLink("");setInviteName("")}}>Invite user</button></header>{notice&&<button className="toast" onClick={()=>setNotice("")}>{notice} ×</button>}
 <div className="access-summary"><div><b>{users.filter(x=>x.status==="active").length}</b><span>Active users</span></div><div><b>{pending.length}</b><span>Pending invitations</span></div><div><b>{users.filter(x=>x.canInvite&&x.status!=="revoked").length}</b><span>Invitation admins</span></div></div>
 {pending.length>0&&<section><div className="section-title"><div><label>INVITATION STACK</label><h2>Waiting to join</h2></div><span>{pending.length} pending</span></div><div className="user-list">{pending.map(user=><UserRow key={user.id} user={user} onEdit={setEditing} onResend={resend} onEmailMyself={emailMyself}/>)}</div></section>}
 <section><div className="section-title"><div><label>TEAM ACCESS</label><h2>Users</h2></div></div><div className="user-list">{active.map(user=><UserRow key={user.id} user={user} onEdit={setEditing} onNotify={notify} maxActivityScore={maxActivityScore}/>)}</div></section>
 </section>{(inviteOpen||editing)&&<div className="access-overlay" onMouseDown={()=>{setInviteOpen(false);setEditing(null)}}><div className="access-panel" onMouseDown={event=>event.stopPropagation()}><button className="close" onClick={()=>{setInviteOpen(false);setEditing(null)}}>×</button>{inviteOpen?<InviteForm dimensions={dimensions} link={link} initialName={inviteName} onInvited={(user,newLink,channel,delivery)=>{setUsers(items=>[user,...items.filter(item=>item.id!==user.id)]);if(channel==="whatsapp")setLink(newLink);else{setNotice(delivery?.sent?`Invitation sent to ${user.email}`:`Invitation created, but the email didn't send — ${delivery?.reason||"unknown reason"}`);setInviteOpen(false)}}}/>:<AccessForm user={editing!} dimensions={dimensions} onSave={save}/>}</div></div>}</main>
}
function UserRow({user,onEdit,onNotify,onResend,onEmailMyself,maxActivityScore}:{user:User;onEdit:(user:User)=>void;onNotify?:(user:User)=>void;onResend?:(user:User)=>void;onEmailMyself?:(user:User)=>void;maxActivityScore?:number}){return <article className={`user-row ${user.status}`}><span className="user-avatar">{user.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}</span><div className="identity"><b>{user.name}</b><small>{user.company_name?`${user.company_name} · `:""}{user.email}{user.email_verified_at?" · Verified":""}</small>{user.status==="active"&&<small className="last-active">{lastActive(user.last_active_at)}</small>}{user.status==="active"&&<div className="activity-meter" title={activityTitle(user)}><div className="activity-meter-bar" style={{width:`${activityPct(user,maxActivityScore||1)}%`}}/></div>}{user.status==="pending"&&deliveryBadge(user)}</div><span className={`role role-${user.role}`}>{roleNames[user.role]}</span><div className="scope"><b>{user.role==="site_admin"?"All areas":[...user.projects,...user.meetings,...user.topics].slice(0,2).join(" · ")||"Relationship-based access"}</b><small>{user.status==="pending"?"Invitation pending":user.status==="revoked"?"Access revoked":user.canInvite?"Can invite users":"No invitation rights"}</small></div><div className="row-actions">{onNotify&&user.status==="active"&&<button className="manage" onClick={()=>onNotify(user)}>Send task summary</button>}{onResend&&user.status==="pending"&&<button className="manage" onClick={()=>onResend(user)}>Resend invitation</button>}{onEmailMyself&&user.status==="pending"&&<button className="manage" onClick={()=>onEmailMyself(user)}>Email invite myself</button>}<button className="manage gear" onClick={()=>onEdit(user)}>⚙ Manage access</button></div></article>}
function InviteForm({dimensions,link,initialName,onInvited}:{dimensions:Dimension[];link:string;initialName?:string;onInvited:(user:User,link:string,channel:"email"|"whatsapp",delivery?:{sent:boolean;reason?:string})=>void}){
 const[email,setEmail]=useState(""),[name,setName]=useState(initialName||""),[phone,setPhone]=useState(""),[channel,setChannel]=useState<"email"|"whatsapp">("email"),[role,setRole]=useState<Role>("collaborator"),[canInvite,setCanInvite]=useState(false),[projects,setProjects]=useState<string[]>([]),[meetings,setMeetings]=useState<string[]>([]),[topics,setTopics]=useState<string[]>([]),[error,setError]=useState(""),[matchedTasks,setMatchedTasks]=useState<{subject:string}[]>([]);
 // Live lookup as the name is typed — lets an admin see, before sending,
 // that this invite will also bundle in someone's existing open tasks
 // (e.g. an external contact already named as a recipient somewhere).
 // Debounced so it doesn't fire on every keystroke; the actual matching
 // (and what ends up in the email) happens again server-side at send time.
 useEffect(()=>{if(!name.trim()||channel!=="email"){setMatchedTasks([]);return}const timer=setTimeout(()=>{fetch(`/api/tasks/match-name?name=${encodeURIComponent(name.trim())}`).then(r=>r.json()).then(data=>setMatchedTasks(data.tasks||[])).catch(()=>{})},400);return()=>clearTimeout(timer)},[name,channel]);
 const submit=async()=>{const response=await fetch("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,name,phone,inviteChannel:channel,role,canInvite,projects,meetings,topics})});const data=await response.json();if(response.ok)onInvited(data.user,`${location.origin}${data.inviteLink}`,data.channel,data.delivery);else setError(data.error)};
 const whatsapp=`https://wa.me/${phone.replace(/\D/g,"")}?text=${encodeURIComponent(`You have been invited to Task AI. Complete your profile and check your tasks: ${link}`)}`;
 return <><label>NEW INVITATION</label><h2>Invite a user</h2><p className="hint">Prepare a secure invitation by email or WhatsApp. The user completes their own profile.</p>{link?<div className="invite-success"><b>Invitation ready</b><p>This single-use link expires after seven days. Send it via WhatsApp.</p><input readOnly value={link}/><div className="share-actions"><button onClick={()=>navigator.clipboard.writeText(link)}>Copy link</button><a href={whatsapp} target="_blank" rel="noreferrer">Open WhatsApp</a></div></div>:<div className="access-form"><Field title="Delivery channel"><select value={channel} onChange={e=>setChannel(e.target.value as "email"|"whatsapp")}><option value="email">Email</option><option value="whatsapp">WhatsApp</option></select></Field><div className="two"><Field title="Email to confirm"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></Field>{channel==="whatsapp"?<Field title="WhatsApp number"><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+43…"/></Field>:<Field title="Known name (optional)"><input value={name} onChange={e=>setName(e.target.value)} placeholder="User completes their profile"/>{matchedTasks.length>0&&<small className="match-hint">✓ {matchedTasks.length} open task{matchedTasks.length===1?"":"s"} reference{matchedTasks.length===1?"s":""} this name — they'll be included in the invitation email.</small>}</Field>}</div><Field title="Role"><select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="collaborator">Collaborator — read & write</option><option value="readonly">Read-only recipient</option><option value="area_admin">Project / Meeting Admin</option><option value="site_admin">Site Admin — full rights</option></select></Field>{role==="area_admin"&&<label className="checkline"><input type="checkbox" checked={canInvite} onChange={e=>setCanInvite(e.target.checked)}/> Allow invitations within assigned areas</label>}<Scopes dimensions={dimensions} values={{projects,meetings,topics}} setters={{projects:setProjects,meetings:setMeetings,topics:setTopics}}/><small className="default-note">Area access is additive. Collaborators can also access individual tasks where they are owner, coworker, or recipient.</small>{error&&<p className="error">{error}</p>}<button className="save" disabled={!email.includes("@")||channel==="whatsapp"&&!phone.trim()} onClick={submit}>Generate secure invitation</button></div>}</>}
function AccessForm({user,dimensions,onSave}:{user:User;dimensions:Dimension[];onSave:(user:User)=>void}){const[draft,setDraft]=useState({...user});const set=(key:keyof User,value:unknown)=>setDraft(current=>({...current,[key]:value}));return <><label>ACCESS RIGHTS</label><h2>{user.name}</h2><p className="hint">Changes take effect immediately for this local prototype.</p><div className="access-form"><Field title="Role"><select value={draft.role} onChange={e=>set("role",e.target.value)}><option value="site_admin">Site Admin — full rights</option><option value="area_admin">Project / Meeting Admin</option><option value="collaborator">Collaborator — read & write</option><option value="readonly">Read-only recipient</option></select></Field>{draft.role==="area_admin"&&<label className="checkline"><input type="checkbox" checked={draft.canInvite} onChange={e=>set("canInvite",e.target.checked)}/> Can invite users within assigned areas</label>}<Scopes dimensions={dimensions} values={draft} setters={{projects:value=>set("projects",value),meetings:value=>set("meetings",value),topics:value=>set("topics",value)}}/><div className="panel-actions"><button className="revoke" onClick={()=>onSave({...draft,status:draft.status==="revoked"?"active":"revoked"})}>{draft.status==="revoked"?"Restore access":"Revoke access"}</button><button className="save" onClick={()=>onSave(draft)}>Save access</button></div></div></>}
// ContactPicklist renders its own <label> (matching app/TaskApp.js's
// Coworkers/Recipients fields, same component) — not wrapped in Field
// here, since Field's <label> would nest inside it. showAvatar is off:
// project/meeting/topic names aren't people, and an initials circle next
// to "Customer Pilot" doesn't mean anything the way it does next to a name.
function Scopes({dimensions,values,setters}:{dimensions:Dimension[];values:{projects:string[];meetings:string[];topics:string[]};setters:Record<"projects"|"meetings"|"topics",(value:string[])=>void>}){return <div className="scopes">{(["project","meeting","topic"] as const).map(type=>{const key=`${type}s` as "projects"|"meetings"|"topics";return <ContactPicklist key={type} label={`${type[0].toUpperCase()+type.slice(1)} access`} value={values[key]} onChange={setters[key]} options={dimensions.filter(item=>item.type===type).map(item=>item.value)} showAvatar={false} allowCreate={false} hint="Type to search; none means no additional scope limit."/>})}</div>}
function Field({title,children}:{title:string;children:React.ReactNode}){return <label className="access-field"><span>{title}</span>{children}</label>}
// @ts-nocheck -- preserved prototype UI; production boundaries are typed and tested.
