// @ts-nocheck -- preserved prototype UI; production boundaries are typed and tested.
"use client";
import { useEffect, useMemo, useState } from "react";
import "./users.css";
type Role="site_admin"|"area_admin"|"collaborator"|"readonly";
type User={id:number;email:string;name:string;company_name?:string;email_verified_at?:string;phone?:string;invite_channel?:"email"|"whatsapp";invite_expires_at?:string;role:Role;status:"pending"|"active"|"revoked";canInvite:boolean;projects:string[];meetings:string[];topics:string[];last_active_at?:string|null};
const lastActive=(iso?:string|null)=>{if(!iso)return"Never signed in";const then=new Date(iso).getTime(),minutes=Math.round((Date.now()-then)/60000);if(minutes<1)return"Active just now";if(minutes<60)return`Active ${minutes}m ago`;if(minutes<1440)return`Active ${Math.round(minutes/60)}h ago`;return`Last active ${new Date(iso).toLocaleDateString("en-GB",{day:"numeric",month:"short"})}`};
type Dimension={type:"project"|"meeting"|"topic";value:string};
const roleNames:Record<Role,string>={site_admin:"Site Admin",area_admin:"Project / Meeting Admin",collaborator:"Collaborator",readonly:"Read-only recipient"};
export default function UsersPage(){
 const[users,setUsers]=useState<User[]>([]),[dimensions,setDimensions]=useState<Dimension[]>([]),[editing,setEditing]=useState<User|null>(null),[inviteOpen,setInviteOpen]=useState(false),[link,setLink]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{const response=await fetch("/api/users");const data=await response.json();if(response.ok){setUsers(data.users);setDimensions(data.dimensions)}else setNotice(data.error)};
 useEffect(()=>{void load()},[]);
 const pending=users.filter(user=>user.status==="pending"),active=users.filter(user=>user.status!=="pending");
 const save=async(user:User)=>{const response=await fetch("/api/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(user)});const data=await response.json();if(response.ok){setUsers(items=>items.map(item=>item.id===data.user.id?data.user:item));setEditing(null);setNotice("Access rights saved") }else setNotice(data.error)};
 const notify=async(user:User)=>{const response=await fetch("/api/users/notify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({userId:user.id})});const data=await response.json();setNotice(response.ok?(data.sent?`Sent ${user.name} their pending tasks (${data.count})`:`Not sent — ${data.reason||"Resend isn't configured yet"}`):data.error)};
 return <main className="users-shell"><aside className="users-side"><a className="users-logo" href="/">Task <b>AI</b></a><nav><a href="/">← Action items</a><a className="active" href="/users">Users & access</a><a href="/email-preview">Email notifications</a></nav><div className="signed"><span>RF</span><div><b>Rizan Flenner</b><small>Site Admin</small></div></div></aside><section className="users-work"><header><div><label>ADMINISTRATION</label><h1>Users & access</h1><p>Invite people and control exactly which work areas they can access.</p></div><button className="invite" onClick={()=>{setInviteOpen(true);setLink("")}}>Invite user</button></header>{notice&&<button className="toast" onClick={()=>setNotice("")}>{notice} ×</button>}
 <div className="access-summary"><div><b>{users.filter(x=>x.status==="active").length}</b><span>Active users</span></div><div><b>{pending.length}</b><span>Pending invitations</span></div><div><b>{users.filter(x=>x.canInvite&&x.status!=="revoked").length}</b><span>Invitation admins</span></div></div>
 {pending.length>0&&<section><div className="section-title"><div><label>INVITATION STACK</label><h2>Waiting to join</h2></div><span>{pending.length} pending</span></div><div className="user-list">{pending.map(user=><UserRow key={user.id} user={user} onEdit={setEditing}/>)}</div></section>}
 <section><div className="section-title"><div><label>TEAM ACCESS</label><h2>Users</h2></div></div><div className="user-list">{active.map(user=><UserRow key={user.id} user={user} onEdit={setEditing} onNotify={notify}/>)}</div></section>
 </section>{(inviteOpen||editing)&&<div className="access-overlay" onMouseDown={()=>{setInviteOpen(false);setEditing(null)}}><div className="access-panel" onMouseDown={event=>event.stopPropagation()}><button className="close" onClick={()=>{setInviteOpen(false);setEditing(null)}}>×</button>{inviteOpen?<InviteForm dimensions={dimensions} link={link} onInvited={(user,newLink,channel,delivery)=>{setUsers(items=>[user,...items.filter(item=>item.id!==user.id)]);if(channel==="whatsapp")setLink(newLink);else{setNotice(delivery?.sent?`Invitation sent to ${user.email}`:`Invitation created, but the email didn't send — ${delivery?.reason||"unknown reason"}`);setInviteOpen(false)}}}/>:<AccessForm user={editing!} dimensions={dimensions} onSave={save}/>}</div></div>}</main>
}
function UserRow({user,onEdit,onNotify}:{user:User;onEdit:(user:User)=>void;onNotify?:(user:User)=>void}){return <article className={`user-row ${user.status}`}><span className="user-avatar">{user.name.split(" ").map(x=>x[0]).slice(0,2).join("").toUpperCase()}</span><div className="identity"><b>{user.name}</b><small>{user.company_name?`${user.company_name} · `:""}{user.email}{user.email_verified_at?" · Verified":""}</small>{user.status==="active"&&<small className="last-active">{lastActive(user.last_active_at)}</small>}</div><span className={`role role-${user.role}`}>{roleNames[user.role]}</span><div className="scope"><b>{user.role==="site_admin"?"All areas":[...user.projects,...user.meetings,...user.topics].slice(0,2).join(" · ")||"Relationship-based access"}</b><small>{user.status==="pending"?"Invitation pending":user.status==="revoked"?"Access revoked":user.canInvite?"Can invite users":"No invitation rights"}</small></div>{onNotify&&user.status==="active"&&<button className="manage" onClick={()=>onNotify(user)}>Send task summary</button>}<button className="manage" onClick={()=>onEdit(user)}>Manage</button></article>}
function InviteForm({dimensions,link,onInvited}:{dimensions:Dimension[];link:string;onInvited:(user:User,link:string,channel:"email"|"whatsapp",delivery?:{sent:boolean;reason?:string})=>void}){
 const[email,setEmail]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[channel,setChannel]=useState<"email"|"whatsapp">("email"),[role,setRole]=useState<Role>("collaborator"),[canInvite,setCanInvite]=useState(false),[projects,setProjects]=useState<string[]>([]),[meetings,setMeetings]=useState<string[]>([]),[topics,setTopics]=useState<string[]>([]),[error,setError]=useState("");
 const submit=async()=>{const response=await fetch("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,name,phone,inviteChannel:channel,role,canInvite,projects,meetings,topics})});const data=await response.json();if(response.ok)onInvited(data.user,`${location.origin}${data.inviteLink}`,data.channel,data.delivery);else setError(data.error)};
 const whatsapp=`https://wa.me/${phone.replace(/\D/g,"")}?text=${encodeURIComponent(`You have been invited to Task AI. Complete your profile and check your tasks: ${link}`)}`;
 return <><label>NEW INVITATION</label><h2>Invite a user</h2><p className="hint">Prepare a secure invitation by email or WhatsApp. The user completes their own profile.</p>{link?<div className="invite-success"><b>Invitation ready</b><p>This single-use link expires after seven days. Send it via WhatsApp.</p><input readOnly value={link}/><div className="share-actions"><button onClick={()=>navigator.clipboard.writeText(link)}>Copy link</button><a href={whatsapp} target="_blank" rel="noreferrer">Open WhatsApp</a></div></div>:<div className="access-form"><Field title="Delivery channel"><select value={channel} onChange={e=>setChannel(e.target.value as "email"|"whatsapp")}><option value="email">Email</option><option value="whatsapp">WhatsApp</option></select></Field><div className="two"><Field title="Email to confirm"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></Field>{channel==="whatsapp"?<Field title="WhatsApp number"><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+43…"/></Field>:<Field title="Known name (optional)"><input value={name} onChange={e=>setName(e.target.value)} placeholder="User completes their profile"/></Field>}</div><Field title="Role"><select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="collaborator">Collaborator — read & write</option><option value="readonly">Read-only recipient</option><option value="area_admin">Project / Meeting Admin</option><option value="site_admin">Site Admin — full rights</option></select></Field>{role==="area_admin"&&<label className="checkline"><input type="checkbox" checked={canInvite} onChange={e=>setCanInvite(e.target.checked)}/> Allow invitations within assigned areas</label>}<Scopes dimensions={dimensions} values={{projects,meetings,topics}} setters={{projects:setProjects,meetings:setMeetings,topics:setTopics}}/><small className="default-note">Area access is additive. Collaborators can also access individual tasks where they are owner, coworker, or recipient.</small>{error&&<p className="error">{error}</p>}<button className="save" disabled={!email.includes("@")||channel==="whatsapp"&&!phone.trim()} onClick={submit}>Generate secure invitation</button></div>}</>}
function AccessForm({user,dimensions,onSave}:{user:User;dimensions:Dimension[];onSave:(user:User)=>void}){const[draft,setDraft]=useState({...user});const set=(key:keyof User,value:unknown)=>setDraft(current=>({...current,[key]:value}));return <><label>ACCESS RIGHTS</label><h2>{user.name}</h2><p className="hint">Changes take effect immediately for this local prototype.</p><div className="access-form"><Field title="Role"><select value={draft.role} onChange={e=>set("role",e.target.value)}><option value="site_admin">Site Admin — full rights</option><option value="area_admin">Project / Meeting Admin</option><option value="collaborator">Collaborator — read & write</option><option value="readonly">Read-only recipient</option></select></Field>{draft.role==="area_admin"&&<label className="checkline"><input type="checkbox" checked={draft.canInvite} onChange={e=>set("canInvite",e.target.checked)}/> Can invite users within assigned areas</label>}<Scopes dimensions={dimensions} values={draft} setters={{projects:value=>set("projects",value),meetings:value=>set("meetings",value),topics:value=>set("topics",value)}}/><div className="panel-actions"><button className="revoke" onClick={()=>onSave({...draft,status:draft.status==="revoked"?"active":"revoked"})}>{draft.status==="revoked"?"Restore access":"Revoke access"}</button><button className="save" onClick={()=>onSave(draft)}>Save access</button></div></div></>}
function Scopes({dimensions,values,setters}:{dimensions:Dimension[];values:{projects:string[];meetings:string[];topics:string[]};setters:Record<"projects"|"meetings"|"topics",(value:string[])=>void>}){return <div className="scopes">{(["project","meeting","topic"] as const).map(type=>{const key=`${type}s` as "projects"|"meetings"|"topics";return <Field title={`${type[0].toUpperCase()+type.slice(1)} access`} key={type}><select multiple value={values[key]} onChange={e=>setters[key]([...e.currentTarget.selectedOptions].map(x=>x.value))}>{dimensions.filter(item=>item.type===type).map(item=><option key={item.value}>{item.value}</option>)}</select><small>⌘/Ctrl-click to select several; none means no additional scope limit.</small></Field>})}</div>}
function Field({title,children}:{title:string;children:React.ReactNode}){return <label className="access-field"><span>{title}</span>{children}</label>}
// @ts-nocheck -- preserved prototype UI; production boundaries are typed and tested.
