import { env } from "cloudflare:workers";
async function ensure(){await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS companies (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, normalized_name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL)"),env.DB.prepare("CREATE UNIQUE INDEX IF NOT EXISTS companies_normalized_name_unique ON companies(normalized_name)")]);for(const statement of ["ALTER TABLE users ADD COLUMN company_id INTEGER REFERENCES companies(id)","ALTER TABLE users ADD COLUMN email_verified_at TEXT"]){try{await env.DB.prepare(statement).run()}catch{}}}
async function hash(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function invitation(token:string){const tokenHash=await hash(token);return env.DB.prepare("SELECT id,email,name,role,invite_channel,invite_expires_at,status FROM users WHERE invite_token_hash=?").bind(tokenHash).first<Record<string,unknown>>();}
function invalid(user:Record<string,unknown>|null){if(!user||user.status!=="pending")return "This invitation is invalid or has already been used";if(!user.invite_expires_at||Date.parse(String(user.invite_expires_at))<Date.now())return "This invitation has expired. Ask an administrator to resend it.";return null}
export async function GET(request:Request){await ensure();const token=new URL(request.url).searchParams.get("token");if(!token)return Response.json({error:"Missing invitation token"},{status:400});const user=await invitation(token),error=invalid(user);if(error)return Response.json({error},{status:400});return Response.json({invitation:{email:user!.email,name:user!.name,role:user!.role,channel:user!.invite_channel,expiresAt:user!.invite_expires_at}})}
export async function POST(request:Request){
 await ensure();const {token,firstName,lastName,email,company}=await request.json() as {token?:string;firstName?:string;lastName?:string;email?:string;company?:string};if(!token)return Response.json({error:"Missing invitation token"},{status:400});
 const user=await invitation(token),error=invalid(user);if(error)return Response.json({error},{status:400});
 const cleanFirst=String(firstName||"").trim(),cleanLast=String(lastName||"").trim(),cleanEmail=String(email||"").trim().toLowerCase(),cleanCompany=String(company||"").trim().replace(/\s+/g," ");if(!cleanFirst||!cleanLast)return Response.json({error:"Enter your first and last name"},{status:400});if(!cleanCompany)return Response.json({error:"Enter your company name"},{status:400});if(cleanEmail!==String(user!.email).toLowerCase())return Response.json({error:"Use the email address that received this invitation"},{status:400});
 const now=new Date().toISOString(),normalizedCompany=cleanCompany.toLocaleLowerCase(),name=`${cleanFirst} ${cleanLast}`,oldName=String(user!.name||"");await env.DB.prepare("INSERT OR IGNORE INTO companies (name,normalized_name,created_at) VALUES (?,?,?)").bind(cleanCompany,normalizedCompany,now).run();const companyRow=await env.DB.prepare("SELECT id,name FROM companies WHERE normalized_name=?").bind(normalizedCompany).first<Record<string,unknown>>();const statements=[env.DB.prepare("UPDATE users SET first_name=?,last_name=?,name=?,company_id=?,email_verified_at=?,status='active',invite_token_hash=NULL,accepted_at=? WHERE id=?").bind(cleanFirst,cleanLast,name,companyRow!.id,now,now,user!.id),env.DB.prepare("INSERT OR IGNORE INTO dimension_values (type,value) VALUES ('person',?)").bind(name)];
 if(oldName&&oldName!=="Invited user"&&oldName!==name){const tasks=await env.DB.prepare("SELECT id,owner,collaborators,recipients FROM tasks").all();for(const task of tasks.results as Array<Record<string,unknown>>){const collaborators=JSON.parse(String(task.collaborators||"[]")) as string[],recipients=JSON.parse(String(task.recipients||"[]")) as string[],owner=task.owner===oldName?name:task.owner,nextCollaborators=collaborators.map(value=>value===oldName?name:value),nextRecipients=recipients.map(value=>value===oldName?name:value);if(owner!==task.owner||nextCollaborators.join("\0")!==collaborators.join("\0")||nextRecipients.join("\0")!==recipients.join("\0"))statements.push(env.DB.prepare("UPDATE tasks SET owner=?,collaborators=?,recipients=? WHERE id=?").bind(owner,JSON.stringify(nextCollaborators),JSON.stringify(nextRecipients),task.id))}}
 await env.DB.batch(statements);const secure=new URL(request.url).protocol==="https:"?"; Secure":"";return Response.json({user:{id:user!.id,email:cleanEmail,name,companyName:companyRow!.name,emailVerifiedAt:now}},{headers:{"Set-Cookie":`act_user=${encodeURIComponent(cleanEmail)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000${secure}`}})
}
