import { env } from "cloudflare:workers";
import { renderInvitationEmail, sendWithResend } from "../../lib/email";
type Role="site_admin"|"area_admin"|"collaborator"|"readonly";
type UserInput={id?:number;email?:string;name?:string;phone?:string;inviteChannel?:"email"|"whatsapp";role?:Role;status?:"pending"|"active"|"revoked";canInvite?:boolean;projects?:string[];meetings?:string[];topics?:string[]};
const parse=(value:unknown)=>{try{return JSON.parse(String(value||"[]"))}catch{return[]}};
const fromRow=(row:Record<string,unknown>)=>({...row,canInvite:Boolean(row.can_invite),projects:parse(row.projects),meetings:parse(row.meetings),topics:parse(row.topics),inviteTokenHash:undefined});
async function hash(value:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function ensure(){await env.DB.batch([
 env.DB.prepare("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', first_name TEXT, last_name TEXT, phone TEXT, invite_channel TEXT NOT NULL DEFAULT 'email', can_invite INTEGER NOT NULL DEFAULT 0, projects TEXT NOT NULL DEFAULT '[]', meetings TEXT NOT NULL DEFAULT '[]', topics TEXT NOT NULL DEFAULT '[]', invite_token_hash TEXT, invited_at TEXT, invite_expires_at TEXT, accepted_at TEXT)"),
 env.DB.prepare("CREATE TABLE IF NOT EXISTS companies (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, normalized_name TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL)"),
 env.DB.prepare("CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users(email)"),
 env.DB.prepare("INSERT OR IGNORE INTO users (email,name,role,status,can_invite) VALUES ('rizan@local.test','Rizan Flenner','site_admin','active',1)"),
 env.DB.prepare("INSERT OR IGNORE INTO users (email,name,role,status,can_invite) VALUES ('rizan@flenner.at','Rizan Flenner','site_admin','active',1)"),
]);for(const statement of ["ALTER TABLE users ADD COLUMN first_name TEXT","ALTER TABLE users ADD COLUMN last_name TEXT","ALTER TABLE users ADD COLUMN company_id INTEGER REFERENCES companies(id)","ALTER TABLE users ADD COLUMN email_verified_at TEXT","ALTER TABLE users ADD COLUMN phone TEXT","ALTER TABLE users ADD COLUMN invite_channel TEXT NOT NULL DEFAULT 'email'","ALTER TABLE users ADD COLUMN invite_expires_at TEXT","ALTER TABLE users ADD COLUMN accepted_at TEXT"]){try{await env.DB.prepare(statement).run()}catch{}}}
function cookieValue(request:Request,name:string){const item=request.headers.get("cookie")?.split(";").map(value=>value.trim()).find(value=>value.startsWith(`${name}=`));return item?decodeURIComponent(item.slice(name.length+1)):null}
async function actor(request:Request){const url=new URL(request.url),local=url.hostname==="localhost"||url.hostname==="127.0.0.1";const email=(local?url.searchParams.get("actor")||request.headers.get("x-act-user"):null)||cookieValue(request,"act_user")||request.headers.get("oai-authenticated-user-email")||(local?"rizan@local.test":null);if(!email)return null;return env.DB.prepare("SELECT * FROM users WHERE lower(email)=lower(?) AND status='active'").bind(email).first<Record<string,unknown>>();}
function mayManage(current:Record<string,unknown>|null,target?:UserInput){if(!current)return false;if(current.role==="site_admin")return true;if(current.role!=="area_admin"||!current.can_invite)return false;return target?.role!=="site_admin"&&target?.role!=="area_admin";}
export async function GET(request:Request){await ensure();const current=await actor(request);if(!current||!current.can_invite)return Response.json({error:"Invitation rights required"},{status:403});const result=await env.DB.prepare("SELECT u.*,c.name AS company_name FROM users u LEFT JOIN companies c ON c.id=u.company_id ORDER BY u.status='revoked',u.name COLLATE NOCASE").all();const dimensions=await env.DB.prepare("SELECT type,value FROM dimension_values ORDER BY value COLLATE NOCASE").all();return Response.json({users:result.results.map(row=>fromRow(row as Record<string,unknown>)),dimensions:dimensions.results,current:fromRow(current)});}
export async function POST(request:Request){await ensure();const current=await actor(request),input=await request.json() as UserInput;if(!mayManage(current,input))return Response.json({error:"You cannot invite this role"},{status:403});const email=String(input.email||"").trim().toLowerCase(),name=String(input.name||"Invited user").trim(),phone=String(input.phone||"").replace(/[^\d+]/g,""),channel=input.inviteChannel||"email";if(!email.includes("@"))return Response.json({error:"Enter the email address the user must confirm"},{status:400});if(channel==="whatsapp"&&!phone)return Response.json({error:"Enter a WhatsApp number"},{status:400});const token=crypto.randomUUID()+crypto.randomUUID(),tokenHash=await hash(token),role=input.role||"collaborator",canInvite=role==="area_admin"?Boolean(input.canInvite):false,invitedAt=new Date(),expiresAt=new Date(invitedAt.getTime()+7*86400000);await env.DB.prepare(`INSERT INTO users (email,name,phone,invite_channel,role,status,can_invite,projects,meetings,topics,invite_token_hash,invited_at,invite_expires_at,accepted_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,NULL) ON CONFLICT(email) DO UPDATE SET name=excluded.name,phone=excluded.phone,invite_channel=excluded.invite_channel,role=excluded.role,status='pending',can_invite=excluded.can_invite,projects=excluded.projects,meetings=excluded.meetings,topics=excluded.topics,invite_token_hash=excluded.invite_token_hash,invited_at=excluded.invited_at,invite_expires_at=excluded.invite_expires_at,accepted_at=NULL`).bind(email,name,phone,channel,role,"pending",canInvite?1:0,JSON.stringify(input.projects||[]),JSON.stringify(input.meetings||[]),JSON.stringify(input.topics||[]),tokenHash,invitedAt.toISOString(),expiresAt.toISOString()).run();const user=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first<Record<string,unknown>>();const inviteLink=`/accept?token=${encodeURIComponent(token)}`;let delivery:{sent:boolean;reason?:string;id?:unknown}={sent:false,reason:"WhatsApp invitation selected"};if(channel==="email"){const inviteUrl=new URL(inviteLink,request.url).toString();const message=renderInvitationEmail({name,inviteUrl,invitedBy:String(current?.name||"Your team")});try{delivery=await sendWithResend({...message,to:email,idempotencyKey:`invite-${tokenHash.slice(0,24)}`})}catch(error){delivery={sent:false,reason:error instanceof Error?error.message:"Email delivery failed"}}}return Response.json({user:fromRow(user!),inviteLink,channel,phone,expiresAt:expiresAt.toISOString(),delivery},{status:201});}
 
export async function PATCH(request:Request){await ensure();const current=await actor(request),input=await request.json() as UserInput;if(!input.id||!mayManage(current,input))return Response.json({error:"Not permitted"},{status:403});const existing=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(input.id).first<Record<string,unknown>>();if(!existing)return Response.json({error:"User not found"},{status:404});if(existing.role==="site_admin"&&current?.role!=="site_admin")return Response.json({error:"Only a Site Admin can change this user"},{status:403});const role=input.role||existing.role,canInvite=role==="site_admin"||role==="area_admin"&&Boolean(input.canInvite);await env.DB.prepare("UPDATE users SET name=?,role=?,status=?,can_invite=?,projects=?,meetings=?,topics=? WHERE id=?").bind(input.name??existing.name,role,input.status??existing.status,canInvite?1:0,JSON.stringify(input.projects??parse(existing.projects)),JSON.stringify(input.meetings??parse(existing.meetings)),JSON.stringify(input.topics??parse(existing.topics)),input.id).run();const user=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(input.id).first<Record<string,unknown>>();return Response.json({user:fromRow(user!)});}
