import { asc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { companies, dimensionValues, users } from "../../../db/schema";
import { mayManageRole, type Role } from "../../lib/permissions";
import { publicRequestUrl, requireSameOrigin } from "../../lib/request";
import { randomToken, sha256 } from "../../lib/security";
import { currentActor } from "../../lib/session";
import { renderInvitationEmail, sendWithResend } from "../../lib/email";
type UserInput={id?:number;email?:string;name?:string;phone?:string;inviteChannel?:"email"|"whatsapp";role?:Role;status?:"pending"|"active"|"revoked";canInvite?:boolean;projects?:string[];meetings?:string[];topics?:string[]};
const publicUser=(row:Record<string,unknown>)=>{const safe={...row};delete safe.inviteTokenHash;return safe};
export async function GET(){const actor=await currentActor();if(!actor||!actor.canInvite)return Response.json({error:"Invitation rights required"},{status:403});const rows=await getDb().select({id:users.id,email:users.email,name:users.name,role:users.role,status:users.status,first_name:users.firstName,last_name:users.lastName,phone:users.phone,invite_channel:users.inviteChannel,canInvite:users.canInvite,projects:users.projects,meetings:users.meetings,topics:users.topics,email_verified_at:users.emailVerifiedAt,company_name:companies.name,invite_expires_at:users.inviteExpiresAt}).from(users).leftJoin(companies,eq(companies.id,users.companyId)).orderBy(asc(users.name));const dimensions=await getDb().select().from(dimensionValues).orderBy(dimensionValues.value);return Response.json({users:rows.map(x=>publicUser(x)),dimensions,current:actor})}
export async function POST(request:Request){const invalid=requireSameOrigin(request);if(invalid)return invalid;const actor=await currentActor(),input=await request.json() as UserInput,role=input.role||"collaborator";if(!mayManageRole(actor,role))return Response.json({error:"You cannot invite this role"},{status:403});const email=String(input.email||"").trim().toLowerCase(),name=String(input.name||"Invited user").trim()||"Invited user",phone=String(input.phone||"").replace(/[^\d+]/g,""),channel=input.inviteChannel||"email";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return Response.json({error:"Enter the email address the user must confirm"},{status:400});if(channel==="whatsapp"&&!phone)return Response.json({error:"Enter a WhatsApp number"},{status:400});const token=randomToken(48),tokenHash=sha256(token),invitedAt=new Date(),expiresAt=new Date(Date.now()+7*86400000),canInvite=role==="site_admin"||role==="area_admin"&&Boolean(input.canInvite);const[user]=await getDb().insert(users).values({email,name,phone,inviteChannel:channel,role,status:"pending",canInvite,projects:input.projects||[],meetings:input.meetings||[],topics:input.topics||[],inviteTokenHash:tokenHash,invitedAt,inviteExpiresAt:expiresAt,acceptedAt:null,emailVerifiedAt:null}).onConflictDoUpdate({target:users.email,set:{name,phone,inviteChannel:channel,role,status:"pending",canInvite,projects:input.projects||[],meetings:input.meetings||[],topics:input.topics||[],inviteTokenHash:tokenHash,invitedAt,inviteExpiresAt:expiresAt,acceptedAt:null,emailVerifiedAt:null}}).returning();const inviteLink=`/accept?token=${encodeURIComponent(token)}`;let delivery:{sent:boolean;reason?:string;id?:unknown}={sent:false,reason:"WhatsApp invitation selected"};if(channel==="email"){const message=renderInvitationEmail({name,inviteUrl:publicRequestUrl(request,inviteLink).toString(),invitedBy:actor?.name||"Your team"});const cc=actor?.email&&actor.email!==email?actor.email:undefined;try{delivery=await sendWithResend({...message,to:email,cc,idempotencyKey:`invite-${tokenHash.slice(0,24)}`})}catch(error){delivery={sent:false,reason:error instanceof Error?error.message:"Email delivery failed"}}}return Response.json({user:publicUser(user),inviteLink,channel,phone,expiresAt,delivery},{status:201})}
export async function PATCH(request:Request){const invalid=requireSameOrigin(request);if(invalid)return invalid;const actor=await currentActor(),input=await request.json() as UserInput;if(!input.id)return Response.json({error:"User id required"},{status:400});const[existing]=await getDb().select().from(users).where(eq(users.id,input.id)).limit(1);if(!existing)return Response.json({error:"User not found"},{status:404});const role=input.role||existing.role;if(!mayManageRole(actor,role)||existing.role==="site_admin"&&actor?.role!=="site_admin")return Response.json({error:"Not permitted"},{status:403});const[user]=await getDb().update(users).set({name:input.name??existing.name,role,status:input.status??existing.status,canInvite:role==="site_admin"||role==="area_admin"&&Boolean(input.canInvite),projects:input.projects??existing.projects,meetings:input.meetings??existing.meetings,topics:input.topics??existing.topics}).where(eq(users.id,input.id)).returning();return Response.json({user:publicUser(user)})}
