import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { dimensionValues, tasks } from "../../../db/schema";
import { canCreateTask, canSeeTask, canWriteTask } from "../../lib/permissions";
import { requireSameOrigin } from "../../lib/request";
import { currentActor } from "../../lib/session";
import { describeChanges, recordActivity } from "../../lib/task-activity";
type StoredTask=typeof tasks.$inferSelect; type Input=Partial<StoredTask>&{recurring_meeting?:string}; type DimensionType="project"|"meeting"|"topic"|"person";
const cleanList=(value:unknown)=>Array.isArray(value)?value.map(String).map(x=>x.trim()).filter(Boolean):[];
function values(input:Input){return{subject:String(input.subject||"").trim(),description:String(input.description||""),owner:String(input.owner||"").trim(),collaborators:cleanList(input.collaborators),recipients:cleanList(input.recipients),due:String(input.due||""),source:String(input.source||""),topic:String(input.topic||""),project:String(input.project||""),recurringMeeting:String(input.recurringMeeting??input.recurring_meeting??""),status:String(input.status||"Open"),created:String(input.created||new Date().toISOString()),updates:Array.isArray(input.updates)?input.updates:[]}}
function entries(task:Input):Array<[DimensionType,string]>{return [["project",task.project],["meeting",task.recurringMeeting],["topic",task.topic],["person",task.owner],...cleanList(task.collaborators).map(x=>["person",x]),...cleanList(task.recipients).map(x=>["person",x])].map(([t,v])=>[t as DimensionType,String(v||"").trim()]).filter((x):x is [DimensionType,string]=>Boolean(x[1]))}
async function register(task:Input){for(const[type,value]of entries(task))await getDb().insert(dimensionValues).values({type,value}).onConflictDoNothing()}
async function dimensions(){const rows=await getDb().select().from(dimensionValues).orderBy(dimensionValues.value);return{project:rows.filter(x=>x.type==="project").map(x=>x.value),meeting:rows.filter(x=>x.type==="meeting").map(x=>x.value),topic:rows.filter(x=>x.type==="topic").map(x=>x.value),person:rows.filter(x=>x.type==="person").map(x=>x.value)}}
export async function GET(){const actor=await currentActor();if(!actor)return Response.json({error:"Sign in required"},{status:401});const all=await getDb().select().from(tasks).orderBy(desc(tasks.id));const visible=all.filter(task=>canSeeTask(task,actor));const scoped={project:[...new Set(visible.map(x=>x.project))],meeting:[...new Set(visible.map(x=>x.recurringMeeting))],topic:[...new Set(visible.map(x=>x.topic))],person:[...new Set(visible.flatMap(x=>[x.owner,...x.collaborators,...x.recipients]))]};return Response.json({tasks:visible,dimensions:actor.role==="site_admin"?await dimensions():scoped,actor:{name:actor.name,email:actor.email,role:actor.role,canWrite:actor.role!=="readonly"}})}
export async function POST(request:Request){const invalid=requireSameOrigin(request);if(invalid)return invalid;const actor=await currentActor();if(!actor)return Response.json({error:"Sign in required"},{status:401});const input=values(await request.json());if(!canCreateTask(input,actor))return Response.json({error:"You cannot create this task"},{status:403});if(!input.subject||!input.owner)return Response.json({error:"Subject and owner are required"},{status:400});const[task]=await getDb().insert(tasks).values({...input,createdBy:actor.name,closedAt:input.status==="Closed"?new Date():null}).returning();await register(task);return Response.json({task,dimensions:await dimensions()},{status:201})}
// closedAt tracks the most recent Open/In progress → Closed transition:
// newly closed gets a fresh timestamp, already-closed keeps its original one
// (editing another field on a closed task shouldn't bump its close date),
// reopening clears it. Powers the digest's "Recently closed" section.
export async function PATCH(request:Request){const invalid=requireSameOrigin(request);if(invalid)return invalid;const actor=await currentActor();if(!actor)return Response.json({error:"Sign in required"},{status:401});const body=await request.json() as Input;if(!body.id)return Response.json({error:"Task id is required"},{status:400});const[existing]=await getDb().select().from(tasks).where(eq(tasks.id,body.id)).limit(1);const next={...values(body),id:body.id};if(!existing||!canWriteTask(existing,actor)||!canWriteTask(next,actor))return Response.json({error:"You cannot change this task"},{status:403});const closedAt=next.status!=="Closed"?null:existing.status==="Closed"?existing.closedAt:new Date();const[task]=await getDb().update(tasks).set({...values(body),closedAt}).where(eq(tasks.id,body.id)).returning();await register(task);await recordActivity(task.id,actor.name,describeChanges(existing,task));return Response.json({task,dimensions:await dimensions()})}
